[auth]
enabled = true
site_url = "https://flow-timer-a-luxurious-pwa.vercel.app"
additional_redirect_urls = [
  "http://localhost:5173",
  "http://localhost:5173/auth/callback",
  "https://flow-timer-a-luxurious-pwa.vercel.app/auth/callback"
]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
secure_password_change = false
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 3600


